version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api/:/api/
    command: uvicorn api:app --reload --workers 1 --host 0.0.0.0 --port 18000
    ports:
      - 18000:18000
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    volumes:
      - ./db/pg_db_init.sql:/docker-entrypoint-initdb.d/pg_db_init.sql
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
    postgres_data:
