#!/bin/sh

# Snyk SAST Scanning
run_snyk_sast_scan() {
    echo "Intiating Snyk SAST scanning"
    snyk code test
    echo "Successfully executed Snyk SAST scan"
}


# Snyk SCA Scanning
run_snyk_sca_scan() {
    echo "Intiating Snyk SCA scanning"
    snyk test
    echo "Successfully executed Snyk SCA scan"
}

run_snyk_sast_scan
run_snyk_sca_scan

exit 0
